export const FETCH_PICTURE_START = "FETCH_PICTURE_START";
export const FETCH_PICTURE_SUCCESS = "FETCH_PICTURE_SUCCESS";
export const FETCH_PICTURE_ERROR = "FETCH_PICTURE_ERROR";
export const FETCH_PICTURE = "FETCH_PICTURE";